### ISSUE TITLE
Investigate persistence mechanism for keep data stable between deploys

### ISSUE THREAD

**Issue by izakfr** [fortyoneeight/variant64#100]
When deploying a new version (or having a server crash) we wipe all of the data. Let's use a DB to solve this. This requires some design decisions to be made.

**Comment by izakfr** [comment]
Requirements to account for:
- Two backend instances can both be live at the same time (i.e. during a deploy)
- Client should only be served correct data
- Client should experience very minimal / no downtime during deploys
- Client should receive responses quickly

Potential implementation plan:
Use AWS DynamoDB as a backup for the in-memory store. All of the data for the backend is stored in-memory. All entity updates cause a write to DynamoDB. Read all the data from DynamoDB after restart to re-populate the store.

Only one backend instance has a "write" lock at a time. The service that holds the lock will heartbeat every 10 seconds. They lose the lock once they have not sent a heartbeat for 10 seconds. The new instance will pickup the lock in this case.

The lifecycle looks like:
1. Instance A starts and acquires the lock
2. Instance B reads the whole state into memory
3. Instance A is writing to the database
4. Instance A is continuously heartbeats for the lock 
5. Instance B starts up
6. Instance B polls for the lock
7. Instance A stops sending a heartbeat
8. Instance A writes state until it no longer has the lock
9. Instance B acquires the lock
10. Instance B reads the whole state into memory
11. Instance B is writing to the database

**Comment by izakfr** [comment]
Here is a diagram:
![mermaid-diagram-2022-12-17-103426](https://user-images.githubusercontent.com/18077030/208249452-c9626e2c-c962-4606-83df-951b259b7c0d.svg)

**Comment by jbsummoner** [comment]
This makes sense when there's one application server 

It can load all active games in memory

**Comment by jbsummoner** [comment]
Anything beyond one, we would need to think about
- two application servers potentially having users with a stateful ws connections and how to we make sure their data is consistent

**Comment by izakfr** [comment]
> Anything beyond one, we would need to think about
> 
> * two application servers potentially having users with a stateful ws connections and how to we make sure their data is consistent

For this we can partition each table in DynamoDB on the key. The load balancer can direct requests to each application server based on the ID of the lookup entity. So it would be the same process as before, but with N * 2 instances rather than 2.

**Comment by jbsummoner** [comment]
👍 makes sense to me

LB will in ensure all like subscriptions are pooled to the right application server.

The application server can the write to the database willingly with our contention.

Read the full table for active games on reboot.

The client can reconnect and we resume where we left off.

This should be good.

**Comment by jbsummoner** [comment]
> For this we can partition each table in DynamoDB on the key.

Application server key ?
Or the entity look up key?

**Comment by izakfr** [comment]
> > For this we can partition each table in DynamoDB on the key.
> 
> Application server key ? Or the entity look up key?

On the entity key, we will use some hashing mechanism to decide DB shard (and server shard).

**Comment by jbsummoner** [comment]
Yes makes sense to me.

It would have to be the same from LB to Application Server 

And 

Application Server to DB partition.
